"""PDF Report — ReportLab"""
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import io

def generate_pdf_report(user, file_rec, report) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    T  = ParagraphStyle("T",  parent=styles["Title"],   fontSize=22, textColor=colors.HexColor("#0f0f18"), alignment=TA_CENTER, fontName="Helvetica-Bold")
    S  = ParagraphStyle("S",  parent=styles["Normal"],  fontSize=11, textColor=colors.HexColor("#5a5a78"), alignment=TA_CENTER, spaceAfter=20)
    H  = ParagraphStyle("H",  parent=styles["Heading2"],fontSize=13, textColor=colors.HexColor("#0f0f18"), spaceBefore=14, fontName="Helvetica-Bold")
    B  = ParagraphStyle("B",  parent=styles["Normal"],  fontSize=9.5, textColor=colors.HexColor("#333"), spaceAfter=4, leading=14)
    OK = ParagraphStyle("OK", parent=B, textColor=colors.HexColor("#1a7a4a"))
    W  = ParagraphStyle("W",  parent=B, textColor=colors.HexColor("#b05a00"))

    story = []
    story.append(Paragraph("DataClean AI", T))
    story.append(Paragraph("Automated Data Cleaning Report", S))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#00f5aa")))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}", B))
    story.append(Paragraph(f"<b>User:</b> {user.get('name','')} ({user.get('email','')})", B))
    story.append(Paragraph(f"<b>File:</b> {file_rec.get('original_name','')}", B))
    story.append(Spacer(1, 10))

    data = [
        ["Metric","Before","After","Change"],
        ["Rows", str(file_rec.get("original_rows",0)), str(file_rec.get("clean_rows",0)), f"-{file_rec.get('original_rows',0)-file_rec.get('clean_rows',0)}"],
        ["Cols", str(file_rec.get("original_cols",0)), str(file_rec.get("clean_cols",0)), f"-{file_rec.get('original_cols',0)-file_rec.get('clean_cols',0)}"],
    ]
    t = Table(data, colWidths=[2.2*inch, 1.3*inch, 1.3*inch, 1.3*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0f0f18")),("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),9),("ALIGN",(0,0),(-1,-1),"CENTER"),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#f0f0f8"),colors.white]),
        ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#cccccc")),
        ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),
    ]))
    story.append(Paragraph("Summary", H))
    story.append(t)
    story.append(Spacer(1, 14))

    STEPS = [("encoding","🔡 Encoding"),("columns","🏷 Columns"),("whitespace","✂ Whitespace"),
             ("dtypes","🔢 Data Types"),("dates","📅 Dates"),("categories","🗂 Categories"),
             ("missing","❓ Missing"),("duplicates","🗑 Duplicates"),("outliers","📊 Outliers")]

    story.append(Paragraph("Steps Detail", H))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 8))
    for sid, slabel in STEPS:
        if sid not in report: continue
        r = report[sid]
        story.append(Paragraph(f"<b>{slabel}</b>", B))
        if isinstance(r, dict) and "error" not in r:
            has = any(v and v != 0 and v != {} and v != [] for v in r.values())
            if not has:
                story.append(Paragraph("  ✓ No issues", OK))
            else:
                for k, v in r.items():
                    if v and v != 0 and v != {} and v != []:
                        story.append(Paragraph(f"  • {k}: {v}", B))
        story.append(Spacer(1, 6))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00f5aa")))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Generated by <b>DataClean AI</b>", ParagraphStyle("F", parent=B, alignment=TA_CENTER, textColor=colors.HexColor("#888"))))
    doc.build(story)
    return buf.getvalue()
